name: pnf
channels:
  - pytorch
  - plotly
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - cudatoolkit=11.3.1
  - pip=21.2.2
  - python=3.8
  - pytorch=1.10.1
  - torchvision=0.11.2
  - pip:
    - numpy==1.21.5
    - argparse
    - trimesh
    - matplotlib
    - opencv-python
    - open3d
    - pyyaml
    - scikit-image
    - tqdm
    - ipdb
    - imgaug
    - tensorboard
    - tensorboardX
    - termcolor
    - prefetch-generator
    - tabulate